[package]
name = "client"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
osveijer-chess = { git = "https://github.com/INDAPlus21/osveijer-chess.git" }
linked-hash-map = "0.5.4" 
ggez = "0.7.0"
